### ISSUE TITLE
Final Week TODO list

### ISSUE THREAD

**Issue by rmattson1008** [SEEsuite/colab_scripts#1]
- [ ] get new reddit mentions list and debug edge_list script (its on the dev branch)
- [ ] get mean color for segmentation masks
- [ ] save images in an easier way, in the segmentation masks script
- [x] save hard copies of the image, with a more consistent image name
- [ ] some of the scripts have messy output on cells - save a cleaner version of files
- [x] Fill out readme with a blurb of what each notebook does
- [x] did I add the general english topic model?
